# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NuGetCommand@2
  displayName: "NuGet Restore"
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: PowerShell@2
  displayName: "NET Standard Build"
  inputs:
    targetType: 'inline'
    script: |
      dotnet build .\Source\CSharp\Expressive\Expressive.Standard\Expressive.Standard.csproj -c release
      
      #dotnet build .\Source\CSharp\Expressive\Expressive\Expressive.csproj -c release
      
      #& "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe" -restore .\Source\CSharp\Expressive\Expressive\Expressive.csproj /t:Build /p:Configuration=Release

# - task: MSBuild@1
#   inputs:
#     solution: '**/*.sln'
#     msbuildVersion: '14.0'
#     configuration: 'Release'

- task: MSBuild@1
  displayName: "NET 4.0 Build"
  inputs:
    solution: '**\Expressive.csproj'
    configuration: 'Release'

# - task: VSBuild@1
#   inputs:
#     solution: '**\*.sln'
#     configuration: 'Release'


  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: 
  #       dotnet build .\Source\CSharp\Expressive\Expressive.Standard\Expressive.Standard.csproj -c release
        
  #       C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe .\Source\CSharp\Expressive\Expressive\Expressive.csproj /t:Build /p:Configuration=Release
