name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 2.1.X Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Setup .NET 3.1.X Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore '**\*.csproj'
    - name: Build
      run: dotnet build --configuration Release --no-restore '**\Expressive.csproj'
    - name: Test
      run: dotnet test --no-restore --verbosity normal '**\Expressive.Tests.csproj'
